@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTBhZGY3NWYwNmQ2MjRkM2M5NWU3MTQiLCJ1c2VyVHlwZSI6ImVtcGxveWVlIiwiaWF0IjoxNzc5MjUxNjA4LCJleHAiOjE4MTA3ODc2MDh9.YzcX-T6rp5ecYVKkutj9Xs0nLfcdiNwx85tcWjp7nLs
# @url =  http://localhost:4567
@url =  http://192.168.1.43:4567
# @url =  https://qnr9g6df-4567.inc1.devtunnels.ms

//Register for client
###
GET {{url}}/api/v1/employee/get-services HTTP/1.1
Content-type: application/json


//Register for client
###
POST {{url}}/api/v1/employee/register HTTP/1.1
Content-type: application/json

{
    "fullName": "User",
    "email": "user@gmail.com",
    "phone": "787878787",
    "serviceId": "6a070df0545bbad2ff184c4a",
    "password": "123456",
    "deviceId": "abcdef"
}


//registerVerify
###
POST {{url}}/api/v1/employee/register-verify HTTP/1.1
Content-type: application/json

{
    "token": "huqcEx3tNllWahTSKpaDxsiecUT6Dndw0WRco6yp",
    "otp": "123456"
}

//login
###
POST {{url}}/api/v1/employee/login HTTP/1.1
Content-type: application/json

{
    "email": "sajiv@gmail.com",
    "password": "123456",
    "deviceId": ""
}

//verifyUser
###
POST {{url}}/api/v1/employee/login-verify HTTP/1.1
Content-type: application/json

{
    "token": "uGLbpRNhaRP6rywh1wcLQoWg8mKWRWngQXem76rt",
    "otp": "123456"
}

//forgotPassword
###
POST {{url}}/api/v1/employee/forgot-password HTTP/1.1
Content-type: application/json

{
    "email": "sajiv@gmail.comss"
}

//forgotPasswordVerify
###
POST {{url}}/api/v1/employee/forgot-password-verify HTTP/1.1
Content-type: application/json

{
    "token": "2LdVWneINEQiuYAazy9EV7Jn0nBJwOGUv6f15A4o",
    "otp": "123456",
    "password": "12345678",
    "confirmPassword": "12345678"
}

//get-profile
###
GET {{url}}/api/v1/employee/get-profile HTTP/1.1
Content-type: application/json
Authorization: {{token}}

//update-profile
###
PUT {{url}}/api/v1/employee/update-profile HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "fullName": "Sajivddin",
    "phone": "9508937828",
    "experience": "2",
    "city": "Jaipur",
    "serviceId": "6a070df0545bbad2ff184c4a",
    "availability": "Evening",
    "address": "Jhotwara Kanta",
    "image": ""
}

//create-leave-request
###
POST  {{url}}/api/v1/employee/create-leave-request HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "leaveDate": "1778697000000",
    "reason": "I am not healthy"
}

### Get My Leave Requests
GET {{url}}/api/v1/employee/get-my-leave-requests?page=1&limit=10 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

# {
#     "page": 1,
#     "limit": 10,
#     "status": "" // "pending", "approved", "rejected"
# }



